### PR TITLE
add F-Droid link

### PR DESCRIPTION
**Pull request by niccokunzmann**
- fixes https://github.com/openintents/openintents.github.io/issues/9

### CODE REVIEW

**Comment by friedger** [comment]
There should be a flag when the app is not available on f-droid

**Comment by niccokunzmann** [comment]
Is there an app which is not available on F-Droid?

**Comment by friedger** [comment]
Yes, at the beginning EULAs were not well accepted. Now I lost track.

**Comment by friedger** [comment]
@niccokunzmann You are right, all apps should be on f-droid. So let's merge it and raise a new issue when a product page is not wanted for an app.

**Comment by friedger** [comment]
@niccokunzmann We have 4 on F-droid: https://search.f-droid.org/?q=Openintents&lang=en
and 9 on openintents.org

OI Shopping list is broken also for play because the package name is different than the page.ref (shoppinglist vs shopping)

**Pull request merged**
